replicaCount: 1

image:
  repository: cloud-reg.uisee.com/public/querymingzhu
  pullPolicy: IfNotPresent
  tag: "v0.0.1"


config:
  server:
    port: 1016
  datasource:
    driverName: mysql
    host: 127.0.0.1
    port: 3307
    database: alertsnitch
    username: alertsnitch
    password: alertsnitch
    charset: utf8
  config:
    markdown: |
      明珠项目
      # 明珠
      ## 监控
      ## 发布


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: querymingzhu.uisee.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false