apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "querymingzhu.fullname" . }}
  labels:
    {{- include "querymingzhu.labels" . | nindent 4 }}
data: 
  application.yml: |
{{ toYaml .Values.config | indent 4 }}
